#!/usr/bin/env bash

function StartHomeAssistant {
  if pgrep -f '[/]usr/local/bin/hass -c /config' >/dev/null; then
    echo "Home Assistant is already running on /config."
    return 0
  fi

  echo "Copy configuration.yaml"
  cp -f .devcontainer/configuration.yaml /config || { echo ".devcontainer/configuration.yaml is missing!"; return 1; }

  echo "Copy the custom component"
  mkdir -p /config/custom_components
  rm -rf /config/custom_components/esxi_stats
  cp -r custom_components/esxi_stats /config/custom_components/ || { echo "Could not copy the custom component"; return 1; }

  echo "Start Home Assistant"
  hass -c /config
}

function UpgradeHomeAssistantDev {
  python -m pip install --upgrade homeassistant --root-user-action ignore
}

function SetHomeAssistantVersion {
  read -p 'Version: ' version
  python -m pip install --upgrade homeassistant==$version
}

function HomeAssistantConfigCheck {
  hass -c /config --script check_config
}

function InstallTabNine {
  echo "Enable TabNine autocomplete"
  mkdir -p /root/.config/TabNine
  cp -f .devcontainer/tabnine_config.json /root/.config/TabNine
  while [ -z "$CLOUD_KEY" ]; do
    echo "Enter cloudkey:"
    read CLOUD_KEY
  done
  sed -i "s/REPLACE_CLOUD_KEY/$CLOUD_KEY/g" /root/.config/TabNine/tabnine_config.json
  echo "TabNine autocomplete done!"
}
